In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data={
    "name":['alice','bob','charie','david','eva','alice'],
    "age":[20,30,35,np.nan,29,25],
    "department":['Hr','IT','Finance','IT','HR','HR'],
    "salary":[50000,60000,70000,62000,np.nan,50000]
}
print(data)

{'name': ['alice', 'bob', 'charie', 'david', 'eva', 'alice'], 'age': [20, 30, 35, nan, 29, 25], 'department': ['Hr', 'IT', 'Finance', 'IT', 'HR', 'HR'], 'salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [4]:
df=pd.DataFrame(data)
print(df)

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0

adding a new column:insert()

In [8]:
#df.insert(loc,column name,data list)
df.insert(0,'id',[101,104,321,122,231,452])
df

    id    name   age department   salary
0  101   alice  20.0         Hr  50000.0
1  104     bob  30.0         IT  60000.0
2  321  charie  35.0    Finance  70000.0
3  122   david   NaN         IT  62000.0
4  231     eva  29.0         HR      NaN
5  452   alice  25.0         HR  50000.0

updating value:loc()

In [9]:
#df.loc[row index,'column name']=value
df.loc[3,'salary']=75000
df

    id    name   age department   salary
0  101   alice  20.0         Hr  50000.0
1  104     bob  30.0         IT  60000.0
2  321  charie  35.0    Finance  70000.0
3  122   david   NaN         IT  75000.0
4  231     eva  29.0         HR      NaN
5  452   alice  25.0         HR  50000.0

null value checking

In [11]:
print(df.isnull())
print(df.isnull().sum())

      id   name    age  department  salary
0  False  False  False       False   False
1  False  False  False       False   False
2  False  False  False       False   False
3  False  False   True       False   False
4  False  False  False       False    True
5  False  False  False       False   False
id            0
name          0
age           1
department    0
salary        1
dtype: int64

drop null value:

In [12]:
#df.dropna(axis=0,inplace=True) for rows
#df.dropna(axis=1,inplace=True) for columns
df.dropna(axis=0)

    id    name   age department   salary
0  101   alice  20.0         Hr  50000.0
1  104     bob  30.0         IT  60000.0
2  321  charie  35.0    Finance  70000.0
5  452   alice  25.0         HR  50000.0

In [13]:
df

    id    name   age department   salary
0  101   alice  20.0         Hr  50000.0
1  104     bob  30.0         IT  60000.0
2  321  charie  35.0    Finance  70000.0
3  122   david   NaN         IT  75000.0
4  231     eva  29.0         HR      NaN
5  452   alice  25.0         HR  50000.0

filling null value:-fillna

In [ ]:
#df.fillna(value,inplace=True) you can give mean,median in place of value
df.fillna(0)

    id    name   age department   salary
0  101   alice  20.0         Hr  50000.0
1  104     bob  30.0         IT  60000.0
2  321  charie  35.0    Finance  70000.0
3  122   david   0.0         IT  75000.0
4  231     eva  29.0         HR      0.0
5  452   alice  25.0         HR  50000.0

In [15]:
#df['age'].fillna(df['age'].mean(),inplace=True)
df['age'].fillna(df['age'].mean())

0    20.0
1    30.0
2    35.0
3    27.8
4    29.0
5    25.0
Name: age, dtype: float64

Interpulation:filling na with estimate value(preserve data integrity,smooth trands,avoid data loss):- interpolate()

In [ ]:
#df.interpolate(method="linear or polynomial or time or quadratic or qubic or etc. ",axis=0,inplace=True)
df.interpolate(method='linear',axis=0)
#uesed with:-
#Timer series data
#numeric data with trends
#avoid dropping rows

C:\Users\surya\AppData\Local\Temp\ipykernel_23708\3138138508.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear',axis=0)

    id    name   age department   salary
0  101   alice  20.0         Hr  50000.0
1  104     bob  30.0         IT  60000.0
2  321  charie  35.0    Finance  70000.0
3  122   david  32.0         IT  75000.0
4  231     eva  29.0         HR  62500.0
5  452   alice  25.0         HR  50000.0

In [20]:
df['age'].interpolate(method='cubic',axis=0)

0    20.000000
1    30.000000
2    35.000000
3    33.678571
4    29.000000
5    25.000000
Name: age, dtype: float64

Sorting the data: Alphabetically

In [8]:
#short value in one column
#df.sort_values(by='column name',True/False,inplace=True)
df.sort_values(by='age',ascending=False)

     name   age department   salary
2  charie  35.0    Finance  70000.0
1     bob  30.0         IT  60000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0
0   alice  20.0         Hr  50000.0
3   david   NaN         IT  62000.0

In [9]:
df.sort_values(by='age',ascending=True)

     name   age department   salary
0   alice  20.0         Hr  50000.0
5   alice  25.0         HR  50000.0
4     eva  29.0         HR      NaN
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0

In [ ]:
#Sorting multiple column data
df.sort_values(by=['name','age','salary'],ascending=False)
#it is not correct because list first column get first priority

     name   age department   salary
4     eva  29.0         HR      NaN
3   david   NaN         IT  62000.0
2  charie  35.0    Finance  70000.0
1     bob  30.0         IT  60000.0
5   alice  25.0         HR  50000.0
0   alice  20.0         Hr  50000.0

In [14]:
df.sort_values(by=['name','age','salary'],ascending=[True,False,False])

     name   age department   salary
5   alice  25.0         HR  50000.0
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN

Summery statistic

In [15]:
print(df['salary'].mean())
print('------------------------')
print(df['salary'].max())
print('------------------------')
print(df['salary'].min())
print('------------------------')
print(df['salary'].sum())
print('------------------------')

58400.0
------------------------
70000.0
------------------------
50000.0
------------------------
292000.0
------------------------

Grouping the data:

In [18]:
#group_obj_name=df.groupby("col1")["col2"].aggregating function
group_obj=df.groupby('department')['salary'].sum()
print(group_obj)

department
Finance     70000.0
HR          50000.0
Hr          50000.0
IT         122000.0
Name: salary, dtype: float64

In [20]:
#whenever you are grouping multiple columns use list of columns
group_obj=df.groupby(['department','name'])['salary'].sum()
print(group_obj)

department  name
Finance     charie    70000.0
HR          alice     50000.0
            eva           0.0
Hr          alice     50000.0
IT          bob       60000.0
            david     62000.0
Name: salary, dtype: float64

In [21]:
#aggrigation function:std() give standad deviation
df['salary'].std()

np.float64(8532.291603080617)

Merging:

In [24]:
#pd.merge(dataframe1,dataframe2,on='column name',how='type of join')
data2={
    "name":['charlie','mark','bob','david','lorence'],
    "donation":[500,300,1000,4000,600]
}
df2=pd.DataFrame(data2)
print(data)
print(df2)

{'name': ['alice', 'bob', 'charie', 'david', 'eva', 'alice'], 'age': [20, 30, 35, nan, 29, 25], 'department': ['Hr', 'IT', 'Finance', 'IT', 'HR', 'HR'], 'salary': [50000, 60000, 70000, 62000, nan, 50000]}
      name  donation
0  charlie       500
1     mark       300
2      bob      1000
3    david      4000
4  lorence       600

In [28]:
#pd.merge(dataframe1,dataframe2,on='column name',how='type of join')
df_merge=pd.merge(df,df2,on='name',how='inner')
print(df_merge)
df_merge=pd.merge(df,df2,on='name',how='outer')
print(df_merge)
df_merge=pd.merge(df,df2,on='name',how='left')
print(df_merge)
df_merge=pd.merge(df,df2,on='name',how='right')
print(df_merge)

    name   age department   salary  donation
0    bob  30.0         IT  60000.0      1000
1  david   NaN         IT  62000.0      4000
      name   age department   salary  donation
0    alice  20.0         Hr  50000.0       NaN
1    alice  25.0         HR  50000.0       NaN
2      bob  30.0         IT  60000.0    1000.0
3   charie  35.0    Finance  70000.0       NaN
4  charlie   NaN        NaN      NaN     500.0
5    david   NaN         IT  62000.0    4000.0
6      eva  29.0         HR      NaN       NaN
7  lorence   NaN        NaN      NaN     600.0
8     mark   NaN        NaN      NaN     300.0
     name   age department   salary  donation
0   alice  20.0         Hr  50000.0       NaN
1     bob  30.0         IT  60000.0    1000.0
2  charie  35.0    Finance  70000.0       NaN
3   david   NaN         IT  62000.0    4000.0
4     eva  29.0         HR      NaN       NaN
5   alice  25.0         HR  50000.0       NaN
      name   age department   salary  donation
0  charlie   NaN        NaN      NaN       500
1     mark   NaN        NaN      NaN       300
2      bob  30.0         IT  60000.0      1000
3    david   NaN         IT  62000.0      4000
4  lorence   NaN        NaN      NaN       600

In [29]:
df_merge=pd.merge(df,df2,how='cross')
df_merge

    name_x   age department   salary   name_y  donation
0    alice  20.0         Hr  50000.0  charlie       500
1    alice  20.0         Hr  50000.0     mark       300
2    alice  20.0         Hr  50000.0      bob      1000
3    alice  20.0         Hr  50000.0    david      4000
4    alice  20.0         Hr  50000.0  lorence       600
5      bob  30.0         IT  60000.0  charlie       500
6      bob  30.0         IT  60000.0     mark       300
7      bob  30.0         IT  60000.0      bob      1000
8      bob  30.0         IT  60000.0    david      4000
9      bob  30.0         IT  60000.0  lorence       600
10  charie  35.0    Finance  70000.0  charlie       500
11  charie  35.0    Finance  70000.0     mark       300
12  charie  35.0    Finance  70000.0      bob      1000
13  charie  35.0    Finance  70000.0    david      4000
14  charie  35.0    Finance  70000.0  lorence       600
15   david   NaN         IT  62000.0  charlie       500
16   david   NaN         IT  62000.0     mark       300
17   david   NaN         IT  62000.0      bob      1000
18   david   NaN         IT  62000.0    david      4000
19   david   NaN         IT  62000.0  lorence       600
20     eva  29.0         HR      NaN  charlie       500
21     eva  29.0         HR      NaN     mark       300
22     eva  29.0         HR      NaN      bob      1000
23     eva  29.0         HR      NaN    david      4000
24     eva  29.0         HR      NaN  lorence       600
25   alice  25.0         HR  50000.0  charlie       500
26   alice  25.0         HR  50000.0     mark       300
27   alice  25.0         HR  50000.0      bob      1000
28   alice  25.0         HR  50000.0    david      4000
29   alice  25.0         HR  50000.0  lorence       600

Data frame concatination

In [31]:
#concating the data frames vertically(row wise) and horizontally(column wise)
#pd.concate([dataframe1,dataframe2],axis=0,ignore_index=True)
df_concat=pd.concat([df,df2],axis=0,ignore_index=True)#vertically
print(df_concat)
df_concat=pd.concat([df,df2],axis=1,ignore_index=False)#horizontally
print(df_concat)

       name   age department   salary  donation
0     alice  20.0         Hr  50000.0       NaN
1       bob  30.0         IT  60000.0       NaN
2    charie  35.0    Finance  70000.0       NaN
3     david   NaN         IT  62000.0       NaN
4       eva  29.0         HR      NaN       NaN
5     alice  25.0         HR  50000.0       NaN
6   charlie   NaN        NaN      NaN     500.0
7      mark   NaN        NaN      NaN     300.0
8       bob   NaN        NaN      NaN    1000.0
9     david   NaN        NaN      NaN    4000.0
10  lorence   NaN        NaN      NaN     600.0
     name   age department   salary     name  donation
0   alice  20.0         Hr  50000.0  charlie     500.0
1     bob  30.0         IT  60000.0     mark     300.0
2  charie  35.0    Finance  70000.0      bob    1000.0
3   david   NaN         IT  62000.0    david    4000.0
4     eva  29.0         HR      NaN  lorence     600.0
5   alice  25.0         HR  50000.0      NaN       NaN