In [1]:
import pandas as pd
import numpy as np

Feature extraction project:

In [2]:
anime=pd.read_csv(r'anime.csv')
anime.head(5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

create a new column for episod

In [18]:
def extract_episod(text):
    data=""
    flag=False
    for i in text:
        if i==')':
            break
        if i== '(':
            flag=True
            continue
        if flag:
            data+=i
    return data

In [19]:
anime['episods']=anime['Title'].apply(extract_episod)
anime.head()

,Rank,Title,Score,time stamp,episods
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,64 eps
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,24 eps
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,13 eps
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,51 eps
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,10 eps

In [20]:
anime['episods']=anime['episods'].str.replace("eps","")
anime.head()

,Rank,Title,Score,time stamp,episods
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,10

In [21]:
anime['episods'].astype(int).head()

0    64
1    24
2    13
3    51
4    10
Name: episods, dtype: int64

In [16]:
anime.head()

   Rank                                              Title  Score episods
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10     64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07     24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06     13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06     51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05     10

Make a new column for time stamp

In [10]:
def extraction_of_time(text):
    flag=False
    data=""
    count=0
    for i in text:
        if count==19:
            break
        if i==')':
            flag=True
            continue
        if flag:
            data=data+i
            count+=1
    return data

In [11]:
temp=extraction_of_time(anime.loc[0]['Title'])
temp

'Apr 2009 - Jul 2010'

In [12]:
anime['time stamp']=anime['Title'].apply(extraction_of_time)
anime.head()

,Rank,Title,Score,time stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019

Find  out highest scored anime:

In [16]:
anime[anime['Score']==anime['Score'].max()]

,Rank,Title,Score,time stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,Apr 2009 - Jul 2010

top 5 scored anime:

In [17]:
anime['Title'].head(5)#because our data is alrady sorted according to score

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

highest episod count:

In [23]:
anime[anime['episods']==anime['episods'].max()]

,Rank,Title,Score,time stamp,episods
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,Oct 2000 - Mar 2002,75