Pandas is useful for data processing and analysis

Importing pandas package

In [1]:
import pandas as pd

a> Series in pandas

In [4]:
s=pd.Series([10,20,30,40,50],name="data")
s

0    10
1    20
2    30
3    40
4    50
Name: data, dtype: int64

In [9]:
s.dtype

dtype('int64')

In [10]:
s.values

array([10, 20, 30, 40, 50])

In [11]:
s.name

'data'

In [12]:
s.index

RangeIndex(start=0, stop=5, step=1)

iloc->location based indexing

In [13]:
s.iloc[3]

np.int64(40)

In [15]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: data, dtype: int64

converting index to label

In [22]:
index=["apple","banana","grapes","orange","strawberry"]
s.index=index
s.name="calories"
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
s.loc['grapes']
#s.iloc['grapes'] will not work here

np.int64(30)

In [27]:
s.loc['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

Dictionary to panda data set

In [29]:
fruit_protien={'avocado':2.0,'guava':2.6,'oranges':0.9,'banana':1.1,'apple':0.3}
s2=pd.Series(fruit_protien)
s2.name='calories'
s2

avocado    2.0
guava      2.6
oranges    0.9
banana     1.1
apple      0.3
Name: calories, dtype: float64

Conditional selection:(and, or and not)

In [30]:
s2[(s2>0.5) & (s2<=2.0)]

avocado    2.0
oranges    0.9
banana     1.1
Name: calories, dtype: float64

In [31]:
s2[(s2>0.5) | (s2<=2.0)]

avocado    2.0
guava      2.6
oranges    0.9
banana     1.1
apple      0.3
Name: calories, dtype: float64

In [32]:
s2[~(s2<1.1)]

avocado    2.0
guava      2.6
banana     1.1
Name: calories, dtype: float64

Modifing series data

In [36]:
s2['apple']=0.1
s2[['apple','guava','avocado']]=[0.3,2.5,2.0]
s2

avocado    2.0
guava      2.5
oranges    0.9
banana     1.1
apple      0.3
Name: calories, dtype: float64

b>Data Frame:-

In [3]:
import numpy as np

In [4]:
data={
    "name":['alice','bob','charie','david','eva','alice'],
    "age":[20,30,35,np.nan,29,25],
    "department":['Hr','IT','Finance','IT','HR','HR'],
    "salary":[50000,60000,70000,62000,np.nan,50000]
}
print(data)

{'name': ['alice', 'bob', 'charie', 'david', 'eva', 'alice'], 'age': [20, 30, 35, nan, 29, 25], 'department': ['Hr', 'IT', 'Finance', 'IT', 'HR', 'HR'], 'salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [5]:
df=pd.DataFrame(data)
df

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0

In [40]:
df.head()

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN

In [41]:
df.head(2)

    name   age department   salary
0  alice  20.0         Hr  50000.0
1    bob  30.0         IT  60000.0

In [42]:
df.tail(3)

    name   age department   salary
3  david   NaN         IT  62000.0
4    eva  29.0         HR      NaN
5  alice  25.0         HR  50000.0

In [43]:
df.tail()

     name   age department   salary
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0

In [44]:
df.iloc[1:3]

     name   age department   salary
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0

In [46]:
df.loc[1:3]

     name   age department   salary
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0

Delete a row from data frame

In [49]:
#df.drop("age") give error
df.drop("age",axis=1)#not deleted from original table

     name department   salary
0   alice         Hr  50000.0
1     bob         IT  60000.0
2  charie    Finance  70000.0
3   david         IT  62000.0
4     eva         HR      NaN
5   alice         HR  50000.0

In [59]:
df.drop("age",axis=1,inplace=True)
df

     name department   salary
0   alice         Hr  50000.0
1     bob         IT  60000.0
2  charie    Finance  70000.0
3   david         IT  62000.0
4     eva         HR      NaN
5   alice         HR  50000.0

add a new colum in data frame

In [60]:
df["age"]=[20,30,35,np.nan,29,25]
df

     name department   salary   age
0   alice         Hr  50000.0  20.0
1     bob         IT  60000.0  30.0
2  charie    Finance  70000.0  35.0
3   david         IT  62000.0   NaN
4     eva         HR      NaN  29.0
5   alice         HR  50000.0  25.0

In [61]:
df.info

<bound method DataFrame.info of      name department   salary   age
0   alice         Hr  50000.0  20.0
1     bob         IT  60000.0  30.0
2  charie    Finance  70000.0  35.0
3   david         IT  62000.0   NaN
4     eva         HR      NaN  29.0
5   alice         HR  50000.0  25.0>

In [62]:
df.describe

<bound method NDFrame.describe of      name department   salary   age
0   alice         Hr  50000.0  20.0
1     bob         IT  60000.0  30.0
2  charie    Finance  70000.0  35.0
3   david         IT  62000.0   NaN
4     eva         HR      NaN  29.0
5   alice         HR  50000.0  25.0>

Broadcasting

In [67]:
df['salary']=df['salary']+5000
df

     name department   salary   age
0   alice         Hr  75000.0  20.0
1     bob         IT  85000.0  30.0
2  charie    Finance  95000.0  35.0
3   david         IT  87000.0   NaN
4     eva         HR      NaN  29.0
5   alice         HR  75000.0  25.0

change column name

In [68]:
df.rename(columns={"department":"dept"},inplace=True)
df

     name     dept   salary   age
0   alice       Hr  75000.0  20.0
1     bob       IT  85000.0  30.0
2  charie  Finance  95000.0  35.0
3   david       IT  87000.0   NaN
4     eva       HR      NaN  29.0
5   alice       HR  75000.0  25.0

In [70]:
df["dept"].unique()

array(['Hr', 'IT', 'Finance', 'HR'], dtype=object)

In [71]:
df["dept"].value_counts()

dept
IT         2
HR         2
Hr         1
Finance    1
Name: count, dtype: int64

In [72]:
df["promoted salary"]=df["salary"]*10

In [73]:
df

     name     dept   salary   age  promoted salary
0   alice       Hr  75000.0  20.0         750000.0
1     bob       IT  85000.0  30.0         850000.0
2  charie  Finance  95000.0  35.0         950000.0
3   david       IT  87000.0   NaN         870000.0
4     eva       HR      NaN  29.0              NaN
5   alice       HR  75000.0  25.0         750000.0

Data Cleaning

a>drop the missing values:-

In [8]:
df.isnull().sum()

name          0
age           1
department    0
salary        1
dtype: int64

In [9]:
df.dropna()

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
5   alice  25.0         HR  50000.0

In [12]:
df.dropna(how="any")

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
5   alice  25.0         HR  50000.0

In [13]:
df.dropna(how="all")

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0

b> Fill the missing values with relative value:-

In [15]:
df.fillna(0)

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   0.0         IT  62000.0
4     eva  29.0         HR      0.0
5   alice  25.0         HR  50000.0

In [16]:
#df["age"].fillna(df["age"].mean(), inplace=True) to save the change in data frame permanently
df["age"].fillna(df["age"].mean())

0    20.0
1    30.0
2    35.0
3    27.8
4    29.0
5    25.0
Name: age, dtype: float64

In [17]:
df["salary"].fillna(df["salary"].mean())

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    58400.0
5    50000.0
Name: salary, dtype: float64

We have tow way to use fillna() method. ie;
a>forward fill

In [18]:
df["age"].fillna(method="ffill")

C:\Users\surya\AppData\Local\Temp\ipykernel_1860\3945036507.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method="ffill")

0    20.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: age, dtype: float64

b> backward fill

In [19]:
df["age"].fillna(method="bfill")

C:\Users\surya\AppData\Local\Temp\ipykernel_1860\2890742411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method="bfill")

0    20.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: age, dtype: float64

change any value in data frame:-

In [20]:
df["name"]=df["name"].replace("alice","mark")
df

     name   age department   salary
0    mark  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN
5    mark  25.0         HR  50000.0

Deal with duplicate values:-

In [23]:
df["age"].fillna(method="ffill",inplace=True)
df

C:\Users\surya\AppData\Local\Temp\ipykernel_1860\2757935224.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(method="ffill",inplace=True)
C:\Users\surya\AppData\Local\Temp\ipykernel_1860\2757935224.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method="ffill",inplace=True)

     name   age department   salary
0    mark  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david  35.0         IT  62000.0
4     eva  29.0         HR      NaN
5    mark  25.0         HR  50000.0

In [25]:
df_duplicate=df[df.duplicated()]
df_duplicate

Empty DataFrame
Columns: [name, age, department, salary]
Index: []

In [26]:
df_duplicate=df[df.duplicated(keep="last")]
df_duplicate

Empty DataFrame
Columns: [name, age, department, salary]
Index: []

In [27]:
df_duplicate=df[df.duplicated(keep="first")]
df_duplicate

Empty DataFrame
Columns: [name, age, department, salary]
Index: []

In [28]:
df.drop_duplicates()

     name   age department   salary
0    mark  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david  35.0         IT  62000.0
4     eva  29.0         HR      NaN
5    mark  25.0         HR  50000.0

In [29]:
df["promoted salary"]=df["salary"]*5
df

     name   age department   salary  promoted salary
0    mark  20.0         Hr  50000.0         250000.0
1     bob  30.0         IT  60000.0         300000.0
2  charie  35.0    Finance  70000.0         350000.0
3   david  35.0         IT  62000.0         310000.0
4     eva  29.0         HR      NaN              NaN
5    mark  25.0         HR  50000.0         250000.0

Invalid function handling: lambda

In [32]:
df["promoted salary"]=df["promoted salary"].apply(lambda x:x/10 if x>65000 else x)
df

     name   age department   salary  promoted salary
0    mark  20.0         Hr  50000.0          25000.0
1     bob  30.0         IT  60000.0          30000.0
2  charie  35.0    Finance  70000.0          35000.0
3   david  35.0         IT  62000.0          31000.0
4     eva  29.0         HR      NaN              NaN
5    mark  25.0         HR  50000.0          25000.0

Using function:-

In [ ]:
def multipling(x):
    return x*2
df["promoted salary"]=df["promoted salary"].apply(multipling)
df

     name   age department   salary  promoted salary
0    mark  20.0         Hr  50000.0          50000.0
1     bob  30.0         IT  60000.0          60000.0
2  charie  35.0    Finance  70000.0          70000.0
3   david  35.0         IT  62000.0          62000.0
4     eva  29.0         HR      NaN              NaN
5    mark  25.0         HR  50000.0          50000.0

Join and Merge:-

In [38]:
data={
    "department":['Hr','IT','Finance','IT','HR','HR'],
    "contact":['whatsap','insta','email','mobile numbe','insta','x']
}
print(data)

{'department': ['Hr', 'IT', 'Finance', 'IT', 'HR', 'HR'], 'contact': ['whatsap', 'insta', 'email', 'mobile numbe', 'insta', 'x']}

In [39]:
df2=pd.DataFrame(data)
df2

  department       contact
0         Hr       whatsap
1         IT         insta
2    Finance         email
3         IT  mobile numbe
4         HR         insta
5         HR             x

In [40]:
pd.concat([df,df2])

     name   age department   salary  promoted salary       contact
0    mark  20.0         Hr  50000.0          50000.0           NaN
1     bob  30.0         IT  60000.0          60000.0           NaN
2  charie  35.0    Finance  70000.0          70000.0           NaN
3   david  35.0         IT  62000.0          62000.0           NaN
4     eva  29.0         HR      NaN              NaN           NaN
5    mark  25.0         HR  50000.0          50000.0           NaN
0     NaN   NaN         Hr      NaN              NaN       whatsap
1     NaN   NaN         IT      NaN              NaN         insta
2     NaN   NaN    Finance      NaN              NaN         email
3     NaN   NaN         IT      NaN              NaN  mobile numbe
4     NaN   NaN         HR      NaN              NaN         insta
5     NaN   NaN         HR      NaN              NaN             x

In [41]:
df

     name   age department   salary  promoted salary
0    mark  20.0         Hr  50000.0          50000.0
1     bob  30.0         IT  60000.0          60000.0
2  charie  35.0    Finance  70000.0          70000.0
3   david  35.0         IT  62000.0          62000.0
4     eva  29.0         HR      NaN              NaN
5    mark  25.0         HR  50000.0          50000.0

In [42]:
df2

  department       contact
0         Hr       whatsap
1         IT         insta
2    Finance         email
3         IT  mobile numbe
4         HR         insta
5         HR             x

In [43]:
pd.merge(df,df2,on="department")

     name   age department   salary  promoted salary       contact
0    mark  20.0         Hr  50000.0          50000.0       whatsap
1     bob  30.0         IT  60000.0          60000.0         insta
2     bob  30.0         IT  60000.0          60000.0  mobile numbe
3  charie  35.0    Finance  70000.0          70000.0         email
4   david  35.0         IT  62000.0          62000.0         insta
5   david  35.0         IT  62000.0          62000.0  mobile numbe
6     eva  29.0         HR      NaN              NaN         insta
7     eva  29.0         HR      NaN              NaN             x
8    mark  25.0         HR  50000.0          50000.0         insta
9    mark  25.0         HR  50000.0          50000.0             x

In [44]:
df

     name   age department   salary  promoted salary
0    mark  20.0         Hr  50000.0          50000.0
1     bob  30.0         IT  60000.0          60000.0
2  charie  35.0    Finance  70000.0          70000.0
3   david  35.0         IT  62000.0          62000.0
4     eva  29.0         HR      NaN              NaN
5    mark  25.0         HR  50000.0          50000.0

In [45]:
df2

  department       contact
0         Hr       whatsap
1         IT         insta
2    Finance         email
3         IT  mobile numbe
4         HR         insta
5         HR             x

Pandas operation using libraries from sklearn

In [12]:
from sklearn.datasets import load_diabetes

In [13]:
dDataSet=load_diabetes()
print(dDataSet)

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10)), 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.]), 'frame': None, 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n', 'feature_names': ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], 'data_filename': 'diabetes_data_raw.csv.gz', 'target_filename': 'diabetes_target.csv.gz', 'data_module': 'sklearn.datasets.data'}

In [11]:
type(dDataSet)

sklearn.utils._bunch.Bunch

In [14]:
ddf=pd.DataFrame(dDataSet.data,columns=dDataSet.feature_names)
ddf

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [13]:
ddf.head(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504

In [14]:
ddf.tail(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
432,0.009016,-0.044642,0.055229,-0.005670,0.057597,0.044719,-0.002903,0.023239,0.055686,0.106617
433,-0.027310,-0.044642,-0.060097,-0.029770,0.046589,0.019980,0.122273,-0.039493,-0.051404,-0.009362
434,0.016281,-0.044642,0.001339,0.008101,0.005311,0.010899,0.030232,-0.039493,-0.045424,0.032059
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
436,-0.056370,-0.044642,-0.074108,-0.050427,-0.024960,-0.047034,0.092820,-0.076395,-0.061176,-0.046641
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

Importing csv file

In [6]:
csvdf=pd.read_csv('C:/Users/surya/Desktop/CODES/MachineLearning/nba.csv')

In [7]:
csvdf

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
csvdf.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [9]:
csvdf.shape

(458, 9)

In [10]:
csvdf.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [11]:
csvdf.tail(20)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Converting dDataSet to csv file.

In [16]:
ddf.to_csv('diabetes.csv')

Creating random value data frame

In [21]:
import numpy as np

In [22]:
random_df=pd.DataFrame(np.random.rand(20,10))
random_df

,0,1,2,3,4,5,6,7,8,9
0,0.782460,0.695867,0.084135,0.671025,0.500429,0.586827,0.061898,0.507653,0.040319,0.428670
1,0.883504,0.989695,0.070156,0.839752,0.187998,0.151439,0.331803,0.075036,0.844373,0.499769
2,0.279423,0.392082,0.697166,0.589467,0.068747,0.764565,0.149965,0.924215,0.287563,0.678386
3,0.296990,0.814651,0.442349,0.119566,0.915343,0.551313,0.286773,0.780372,0.005334,0.402412
4,0.371826,0.075690,0.454413,0.746339,0.012958,0.588599,0.434205,0.085053,0.145787,0.559972
5,0.943347,0.779194,0.544986,0.593482,0.960469,0.817209,0.213096,0.092997,0.246389,0.738711
6,0.652127,0.810741,0.409819,0.223798,0.244821,0.260793,0.407780,0.022345,0.567824,0.398777
7,0.140141,0.767668,0.242451,0.485141,0.417259,0.985468,0.830314,0.323940,0.275764,0.747175
8,0.651956,0.505907,0.256840,0.302751,0.261450,0.173734,0.749605,0.062462,0.760112,0.396747
9,0.512959,0.549853,0.033892,0.401938,0.088860,0.481126,0.168825,0.176486,0.514926,0.521404
10,0.309730,0.445656,0.461001,0.578742,0.929759,0.182982,0.725017,0.775387,0.324991,0.679205
11,0.292540,0.704035,0.321273,0.032877,0.906396,0.841730,0.956956,0.901369,0.593348,0.989428
12,0.606821,0.268927,0.524536,0.432122,0.535374,0.485339,0.614895,0.792971,0.516185,0.359890
13,0.118576,0.633510,0.146878,0.796371,0.120300,0.577683,0.528488,0.943914,0.501535,0.894417
14,0.829322,0.018250,0.304222,0.891440,0.056709,0.741957,0.818071,0.277486,0.754161,0.208426
15,0.643292,0.896911,0.876596,0.295828,0.688636,0.339359,0.048042,0.296141,0.042667,0.973696
16,0.779074,0.156678,0.212900,0.942644,0.323990,0.590709,0.939126,0.841929,0.458997,0.535298
17,0.051348,0.447304,0.170237,0.992279,0.417379,0.897007,0.561431,0.029497,0.083787,0.845340
18,0.457823,0.243187,0.423159,0.934643,0.986946,0.019808,0.234043,0.718948,0.769930,0.204636
19,0.876436,0.306240,0.847077,0.253973,0.985267,0.729267,0.314360,0.430563,0.178751,0.099559

Statistical measures:-

In [2]:
csvdf=pd.read_csv('C:/Users/surya/Desktop/CODES/MachineLearning/nba.csv')
csvdf

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
csvdf.count()

Name        457
Team        457
Number      457
Position    457
Age         457
Height      457
Weight      457
College     373
Salary      446
dtype: int64

In [17]:
csvdf["Salary"].mean()

np.float64(4842684.105381166)

In [16]:
csvdf["Salary"].std()

np.float64(5229237.598910348)

In [19]:
csvdf[["Number","Salary"]].min()

Number        0.0
Salary    30888.0
dtype: float64

In [20]:
csvdf[["Number","Salary"]].max()

Number          99.0
Salary    25000000.0
dtype: float64

For all statistical measures of csvdf: use dedcrive()

In [21]:
csvdf[["Number","Salary"]].describe()

           Number        Salary
count  457.000000  4.460000e+02
mean    17.678337  4.842684e+06
std     15.966090  5.229238e+06
min      0.000000  3.088800e+04
25%      5.000000  1.044792e+06
50%     13.000000  2.839073e+06
75%     25.000000  6.500000e+06
max     99.000000  2.500000e+07

Correlation:
1.Positive Correlation
2.Negative Correlation

In [23]:
csvdf[['Age','Salary','Number']].corr()

             Age    Salary    Number
Age     1.000000  0.213459  0.028724
Salary  0.213459  1.000000 -0.112386
Number  0.028724 -0.112386  1.000000