In [1]:
import pandas as pd
import numpy as np

In [2]:
data={
    "name":['alice','bob','charie','david','eva','alice'],
    "age":[20,30,35,np.nan,29,25],
    "department":['Hr','IT','Finance','IT','HR','HR'],
    "salary":[50000,60000,70000,62000,np.nan,50000]
}
print(data)

{'name': ['alice', 'bob', 'charie', 'david', 'eva', 'alice'], 'age': [20, 30, 35, nan, 29, 25], 'department': ['Hr', 'IT', 'Finance', 'IT', 'HR', 'HR'], 'salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [3]:
df=pd.DataFrame(data)
df

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   NaN         IT  62000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0

select specific area data

In [6]:
df.loc[2:4][["age","salary"]]

    age   salary
2  35.0  70000.0
3   NaN  62000.0
4  29.0      NaN

find out name those have above 22 year

In [7]:
df[df["age"]>22]

     name   age department   salary
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
4     eva  29.0         HR      NaN
5   alice  25.0         HR  50000.0

In [8]:
df[(df["age"]>22) & (df["department"]== "HR")]

    name   age department   salary
4    eva  29.0         HR      NaN
5  alice  25.0         HR  50000.0

fill particular value in each column missing place

In [10]:
values={"name":"absent","age":1,"depatment":"null","salary":100}
df.fillna(value=values)

     name   age department   salary
0   alice  20.0         Hr  50000.0
1     bob  30.0         IT  60000.0
2  charie  35.0    Finance  70000.0
3   david   1.0         IT  62000.0
4     eva  29.0         HR    100.0
5   alice  25.0         HR  50000.0

Groupby function use

Remember you can't see the values of object created after use of groupby function. to see you have to use agregate funtions

In [11]:
group=df.groupby("department")
for i,v in group:
    print(i)
    print(v)

Finance
     name   age department   salary
2  charie  35.0    Finance  70000.0
HR
    name   age department   salary
4    eva  29.0         HR      NaN
5  alice  25.0         HR  50000.0
Hr
    name   age department   salary
0  alice  20.0         Hr  50000.0
IT
    name   age department   salary
1    bob  30.0         IT  60000.0
3  david   NaN         IT  62000.0

In [14]:
group=df.groupby("department")["salary"].sum()
group

department
Finance     70000.0
HR          50000.0
Hr          50000.0
IT         122000.0
Name: salary, dtype: float64

In [17]:
group=df.groupby(["department","name"])["salary"].sum()
group

department  name
Finance     charie    70000.0
HR          alice     50000.0
            eva           0.0
Hr          alice     50000.0
IT          bob       60000.0
            david     62000.0
Name: salary, dtype: float64

Pivot Table: in pivot tables values= always numeric for agrigation

In [21]:
pd.pivot_table(df,values="salary",index="department",columns="name")

name          alice      bob   charie    david
department
Finance         NaN      NaN  70000.0      NaN
HR          50000.0      NaN      NaN      NaN
Hr          50000.0      NaN      NaN      NaN
IT              NaN  60000.0      NaN  62000.0

In [22]:
pd.pivot_table(df,values="salary",index="department",columns="name",aggfunc=sum)

C:\Users\surya\AppData\Local\Temp\ipykernel_21852\3752180833.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,values="salary",index="department",columns="name",aggfunc=sum)

name          alice      bob   charie    david  eva
department
Finance         NaN      NaN  70000.0      NaN  NaN
HR          50000.0      NaN      NaN      NaN  0.0
Hr          50000.0      NaN      NaN      NaN  NaN
IT              NaN  60000.0      NaN  62000.0  NaN

In [23]:
pd.pivot_table(df,values=["salary","age"],index="department",columns="name")

             age                      salary
name       alice   bob charie   eva    alice      bob   charie    david
department
Finance      NaN   NaN   35.0   NaN      NaN      NaN  70000.0      NaN
HR          25.0   NaN    NaN  29.0  50000.0      NaN      NaN      NaN
Hr          20.0   NaN    NaN   NaN  50000.0      NaN      NaN      NaN
IT           NaN  30.0    NaN   NaN      NaN  60000.0      NaN  62000.0

In [24]:
pd.crosstab(df["department"],df["name"])

name        alice  bob  charie  david  eva
department
Finance         0    0       1      0    0
HR              1    0       0      0    1
Hr              1    0       0      0    0
IT              0    1       0      1    0

In [4]:
import seaborn as sns